services:
  app:
    image: ghcr.io/supriaditech/my-portfolio:latest
    container_name: my-portfolio
    restart: unless-stopped
    init: true
    stop_grace_period: 5s
    ports:
      - '0210:3000'
    env_file:
      - path: .env.production
        required: false
